### ISSUE TITLE
Chat bug caused by deferred scripts

### ISSUE THREAD

**Issue by Hri7566** [LapisHusky/mppclone#129]
I brought this up to @DexterHaxxor already but I'm created this issue here for the sake of discussion.

While loading the page, there is a chance for the chat to load incorrectly.

![image](https://user-images.githubusercontent.com/18133844/220824021-b17b294e-882c-4ebd-ba68-abbf11d981b7.png)

**Comment by DexterHaxxor** [comment]
What browser and version are you using? Does it happen in a private tab with plugins disabled?

**Comment by Hri7566** [comment]
this happens between both Firefox and Brave on my machine, no matter what settings are in place
