### ISSUE TITLE
Document the admin messages

### ISSUE THREAD

**Issue by Hri7566** [LapisHusky/mppclone#150]

**Comment by lithiumjs** [comment]
Is there a real need for that? Those endpoints are only usable by staff.

**Comment by Hri7566** [comment]
it's part of the protocol

**Comment by LapisHusky** [comment]
seems like a waste of time to document and keep updated. the purpose of the protocol docs is to allow tons of users to easily see the protocol and develop bots and scripts with it. admin messages may be more frequently added/changed/removed, and we can communicate within staff channels or dms already to explain that. making official documentation seems pointless when most people can't use it.
