### ISSUE TITLE
Delete ebsprite Folder and ebsprite.js

### ISSUE THREAD

**Issue by catnitrogen** [LapisHusky/mppclone#36]
Why Will I Fork Then I Have Storage Full Of It Sudden When This mf Comes By Just To Crash My PC

**Comment by catnitrogen** [comment]
...

**Comment by wolfy01** [comment]
You can delete them from your fork.

**Comment by catnitrogen** [comment]
it takes so long to delete

**Comment by wolfy01** [comment]
Well you only have to do it once anyway

**Comment by catnitrogen** [comment]
ok
