### ISSUE TITLE
DMs fill chat history

### ISSUE THREAD

**Issue by Hri7566** [LapisHusky/mppclone#46]
When chat history is sent to a client, it is received in a truncated form. Since that chat history message includes direct messages on the server-side, direct messages take up space in that backlog and this results in fewer messages showing up in the chat history message.

**Comment by LapisHusky** [comment]
the server tries to make sure there are at least 32 public chat messages in a channel's log at all times, so the true length of the chat log does go beyond 32 if there are DMs
the server does, however, have a hard limit of 256 messages in the log including DMs, if that is overflowed then public chat messages will start being deleted, resulting in some users receiving a shorter chat history
the limit could be increased, but it seems to work fine in most cases right now
