### ISSUE TITLE
Siteban ID is mislabeled

### ISSUE THREAD

**Issue by yourfriendoss** [LapisHusky/mppclone#97]
Siteban ID is sent as `id` while it's actually `_id`

https://github.com/LapisHusky/mppclone/blob/0fb8d4476f4335f6b40093ef68cc75dd7f6a8cb2/client/script.js#L2481
This is supposed to be `$("#siteban input[name=id]").val(part.id);`
as per 
https://github.com/LapisHusky/mppclone/blob/0fb8d4476f4335f6b40093ef68cc75dd7f6a8cb2/client/script.js#L2985

**Comment by Nitsua0615** [comment]
Not a bug, it gets the text value in the element and assigns it to `msg.id`. We don't want to change the value in that textbox, we just want to get its value, which is what this does
